[CmdletBinding()]
param(
    [string] $FixturesDir = ''
)

# tests/run-hook-fixtures.ps1 -- C-01..C-15 fixture driver (#33).
#
# Each fixture under tests/fixtures/hook/*.json declares:
#   {
#     "id":          "C-XX",
#     "description": "...",
#     "env":         { ... per-fixture env overrides; "" deletes ... },
#     "event":       { "tool_name": "...", "tool_input": {...} },
#     "expected":    { "exitCode": 0|2, "stdoutContains": "allow"|"block" }
#   }
#
# Pre-stage: stamp lib/lead-extension.sha256 from on-disk pin files so the
# hook's pin-chain check passes. Trust anchor (install-hook.ps1 SHA) is
# expected to match _ANCHOR_SHA in lead-pretool-hook.py at HEAD --
# CI verifies this implicitly because both files ship together.
#
# Per fixture: build baseline env, apply overrides, pipe event JSON to
# python lib/lead-pretool-hook.py via stdin, capture exit + stdout,
# assert. Print summary; exit 1 on any mismatch.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$RepoRoot = Split-Path -Parent $PSScriptRoot
$LibDir   = Join-Path $RepoRoot 'lib'
$Hook     = Join-Path $LibDir   'lead-pretool-hook.py'
if (-not $FixturesDir) {
    $FixturesDir = Join-Path $PSScriptRoot 'fixtures\hook'
}

# 11-file pin set MIRRORS lead-pretool-hook.py:_PIN_FILES. launch.ps1 lives
# in skill root; the rest in lib/. Order is irrelevant for verification
# but stable for diff-readability.
# v1.1.0: added secret-scan.ps1 + jsonl-watcher.ps1 (W3-NEW2 -- closes the
# orphan-attack surface where helpers shipped outside the pin chain).
$PinFiles = @(
    @{ Name = 'allowlist.json';        Path = Join-Path $LibDir   'allowlist.json' }
    @{ Name = 'path-guard.json';       Path = Join-Path $LibDir   'path-guard.json' }
    @{ Name = 'mcp-allow.json';        Path = Join-Path $LibDir   'mcp-allow.json' }
    @{ Name = 'notify-sh.sha256';      Path = Join-Path $LibDir   'notify-sh.sha256' }
    @{ Name = 'canonicalize-path.py';  Path = Join-Path $LibDir   'canonicalize-path.py' }
    @{ Name = 'allowlist_parser.py';   Path = Join-Path $LibDir   'allowlist_parser.py' }
    @{ Name = 'lead-pretool-hook.py';  Path = Join-Path $LibDir   'lead-pretool-hook.py' }
    @{ Name = 'sanitize-jsonl.py';     Path = Join-Path $LibDir   'sanitize-jsonl.py' }
    @{ Name = 'secret-scan.ps1';       Path = Join-Path $LibDir   'secret-scan.ps1' }
    @{ Name = 'jsonl-watcher.ps1';     Path = Join-Path $LibDir   'jsonl-watcher.ps1' }
    @{ Name = 'launch.ps1';            Path = Join-Path $RepoRoot 'launch.ps1' }
)

function Get-FileSha256Hex {
    param([string] $Path)
    return (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
}

function Ensure-NotifyShPin {
    # lib/notify-sh.sha256 is gitignored by design (.gitignore:10) -- it is
    # per-user-stamped at install time by install.ps1 -RepinNotify against
    # each cloner's local ~/.claude/tools/notify.sh. In CI / fresh clones
    # the file legitimately doesn't exist, which would make Stamp-PinManifest
    # throw "missing pin file".
    #
    # Solution: stub the file with deterministic test content so Stamp can
    # enumerate all 9 pins. The stub diverges from any production install's
    # value (intentionally so -- author's hash is per-user-private), but
    # internally consistent: manifest re-stamp references the stub's SHA.
    # Fixtures test hook DISPATCH correctness; the per-user manifest
    # divergence at this entry is orthogonal to dispatch logic.
    $path = Join-Path $LibDir 'notify-sh.sha256'
    if (Test-Path -LiteralPath $path) { return }
    # Mirror install.ps1 -RepinNotify byte format: 64-hex sha + 2 spaces +
    # "notify.sh" + LF (76 bytes total). Use all-zero hex as the stub
    # sentinel -- deterministic and obvious-not-real on inspection.
    $stubSha = '0' * 64
    $stub = "$stubSha  notify.sh`n"
    [System.IO.File]::WriteAllText($path, $stub, (New-Object System.Text.UTF8Encoding($false)))
}

function Stamp-PinManifest {
    # MIRRORS lib/install-hook.ps1 Write-PinManifest exactly so re-stamping
    # against unchanged pin files is byte-identical to the committed manifest.
    # Format: 3 comment headers + body (name padded to 24 chars + space + hex)
    # + LF terminator + "sha256:<hex>" self-hash + LF.
    $rows = @(
        '# lead-extension.sha256 v3'
        '# Generated by install-hook.ps1; manually editing breaks the integrity contract.'
        '# Last line is sha256:<hex> over all preceding lines (self-hash chain).'
    )
    foreach ($pf in $PinFiles) {
        if (-not (Test-Path -LiteralPath $pf.Path)) {
            throw "missing pin file: $($pf.Path)"
        }
        $sha = Get-FileSha256Hex -Path $pf.Path
        $name = $pf.Name.PadRight(24)
        $rows += "$name $sha"
    }
    $body = ($rows -join "`n") + "`n"
    $bodyBytes = [System.Text.Encoding]::UTF8.GetBytes($body)
    $hasher = [System.Security.Cryptography.SHA256]::Create()
    try {
        $selfHash = ([BitConverter]::ToString($hasher.ComputeHash($bodyBytes))).Replace('-', '').ToLowerInvariant()
    } finally { $hasher.Dispose() }
    $manifest = $body + "sha256:$selfHash`n"
    $outPath = Join-Path $LibDir 'lead-extension.sha256'
    [System.IO.File]::WriteAllText($outPath, $manifest, (New-Object System.Text.UTF8Encoding($false)))
    return $outPath
}

function New-BaselineEnv {
    param([string] $ExtShaPath)
    $tmpWorktree = Join-Path $env:TEMP "lead-agent-tests-$([System.Guid]::NewGuid().ToString('N'))"
    New-Item -ItemType Directory -Path $tmpWorktree -Force | Out-Null
    return @{
        LEAD_AGENT             = '1'
        LEAD_HOOK_SCHEMA       = '3'
        LEAD_AGENT_MODE        = 'BUILDER'
        LEAD_WORKTREE_PARENT   = $tmpWorktree
        LEAD_ALLOWLIST         = (Join-Path $LibDir 'allowlist.json')
        LEAD_PATH_GUARD        = (Join-Path $LibDir 'path-guard.json')
        LEAD_MCP_ALLOW         = (Join-Path $LibDir 'mcp-allow.json')
        LEAD_NOTIFY_SHA256     = (Join-Path $LibDir 'notify-sh.sha256')
        LEAD_EXTENSION_SHA256  = $ExtShaPath
        LEAD_CANONICALIZER     = (Join-Path $LibDir 'canonicalize-path.py')
        LEAD_TOOLS_DIR         = (Join-Path $env:USERPROFILE '.claude\tools')
    }
}

function Invoke-HookFixture {
    param(
        [hashtable] $BaselineEnv,
        [object]    $Fixture
    )
    # Compose env: baseline overlaid with per-fixture overrides; "" deletes.
    $envSet = @{}
    foreach ($k in $BaselineEnv.Keys) { $envSet[$k] = $BaselineEnv[$k] }

    $overrideNames = @()
    if ($Fixture.PSObject.Properties.Name -contains 'env' -and $null -ne $Fixture.env) {
        $props = @($Fixture.env.PSObject.Properties)
        foreach ($prop in $props) {
            $envSet[$prop.Name] = $prop.Value
            $overrideNames += $prop.Name
        }
    }

    # Snapshot caller env for the keys we touch so we can restore.
    $touched = @($BaselineEnv.Keys) + $overrideNames | Select-Object -Unique
    $snapshot = @{}
    foreach ($k in $touched) {
        $snapshot[$k] = [Environment]::GetEnvironmentVariable($k, 'Process')
    }

    try {
        foreach ($k in $touched) {
            $v = $envSet[$k]
            if ($null -eq $v -or $v -eq '') {
                [Environment]::SetEnvironmentVariable($k, $null, 'Process')
            } else {
                [Environment]::SetEnvironmentVariable($k, $v, 'Process')
            }
        }

        $eventJson = $Fixture.event | ConvertTo-Json -Compress -Depth 10

        # Pipe stdin via tempfile + cmd redirection. Direct
        # ProcessStartInfo.RedirectStandardInput on PS5.1/.NET Framework 4.x
        # eagerly writes a UTF-8 BOM to the redirected pipe at StreamWriter
        # construction (verified empirically: 75-byte payload arrived as
        # 78 bytes with EF BB BF prefix). Python's json.loads() rejects BOM.
        # Tempfile path uses UTF8Encoding($false) -- same BOM-less write
        # used by Stamp-PinManifest -- and cmd's "<" redirection passes
        # raw file bytes through without StreamWriter interposition.
        $stdinFile = Join-Path $env:TEMP "lead-agent-fixture-$([System.Guid]::NewGuid().ToString('N')).json"
        [System.IO.File]::WriteAllText($stdinFile, $eventJson, (New-Object System.Text.UTF8Encoding $false))

        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName = $env:ComSpec
        if (-not $psi.FileName) { $psi.FileName = 'cmd.exe' }
        $psi.Arguments = "/c `"python `"$Hook`" < `"$stdinFile`"`""
        $psi.RedirectStandardOutput = $true
        $psi.RedirectStandardError  = $true
        $psi.UseShellExecute = $false
        $psi.CreateNoWindow  = $true
        $proc = [System.Diagnostics.Process]::Start($psi)
        try {
            $stdout = $proc.StandardOutput.ReadToEnd()
            $stderr = $proc.StandardError.ReadToEnd()
            $proc.WaitForExit(15000) | Out-Null
            if (-not $proc.HasExited) {
                $proc.Kill()
                throw "fixture $($Fixture.id) timed out"
            }
            return [pscustomobject]@{
                ExitCode = $proc.ExitCode
                Stdout   = $stdout
                Stderr   = $stderr
            }
        } finally {
            $proc.Dispose()
            Remove-Item -LiteralPath $stdinFile -Force -ErrorAction SilentlyContinue
        }
    } finally {
        foreach ($k in $snapshot.Keys) {
            [Environment]::SetEnvironmentVariable($k, $snapshot[$k], 'Process')
        }
    }
}

# =============================================================================
# Main
# =============================================================================

Write-Host "[run-hook-fixtures] ensuring per-user notify-sh pin stub..." -ForegroundColor Cyan
Ensure-NotifyShPin

Write-Host "[run-hook-fixtures] stamping pin manifest..." -ForegroundColor Cyan
$extShaPath = Stamp-PinManifest
Write-Host "[run-hook-fixtures] manifest: $extShaPath" -ForegroundColor DarkCyan

$baselineEnv = New-BaselineEnv -ExtShaPath $extShaPath
Write-Host "[run-hook-fixtures] baseline worktree: $($baselineEnv.LEAD_WORKTREE_PARENT)" -ForegroundColor DarkCyan

$fixtureFiles = Get-ChildItem -LiteralPath $FixturesDir -Filter 'C-*.json' | Sort-Object Name
if ($fixtureFiles.Count -eq 0) {
    Write-Error "no fixtures found at $FixturesDir"
    exit 2
}

$results  = @()
$pass     = 0
$fail     = 0

foreach ($file in $fixtureFiles) {
    try {
        $fixture = Get-Content -LiteralPath $file.FullName -Raw | ConvertFrom-Json
    } catch {
        $fail++
        $results += [pscustomobject]@{
            Id = $file.BaseName; Status = 'PARSE-FAIL'; Detail = $_.Exception.Message
        }
        continue
    }

    try {
        $r = Invoke-HookFixture -BaselineEnv $baselineEnv -Fixture $fixture
    } catch {
        $fail++
        $results += [pscustomobject]@{
            Id = $fixture.id; Status = 'INVOKE-FAIL'; Detail = $_.Exception.Message
        }
        continue
    }

    $expectedExit = [int]$fixture.expected.exitCode
    $expectedSubstr = $fixture.expected.stdoutContains
    $okExit  = ($r.ExitCode -eq $expectedExit)
    $okStdout = ($r.Stdout -like "*$expectedSubstr*")

    if ($okExit -and $okStdout) {
        $pass++
        $results += [pscustomobject]@{
            Id = $fixture.id; Status = 'PASS';
            Detail = "exit=$($r.ExitCode) stdout~=$expectedSubstr"
        }
    } else {
        $fail++
        $detail = "exit got=$($r.ExitCode) want=$expectedExit; stdout=$($r.Stdout)"
        if ($r.Stderr) { $detail += "; stderr=$($r.Stderr.Trim())" }
        $results += [pscustomobject]@{
            Id = $fixture.id; Status = 'FAIL'; Detail = $detail
        }
    }
}

Write-Host ""
Write-Host "=== fixture results ===" -ForegroundColor Cyan
foreach ($row in $results) {
    $color = switch ($row.Status) {
        'PASS'        { 'Green' }
        default       { 'Red' }
    }
    Write-Host ("  [{0,-12}] {1,-6} {2}" -f $row.Status, $row.Id, $row.Detail) -ForegroundColor $color
}
Write-Host ""
Write-Host "totals: pass=$pass fail=$fail / $($fixtureFiles.Count)" -ForegroundColor Cyan

# Re-stamping the manifest is idempotent when pin files match HEAD; we
# leave it in place. If a contributor changed a pin file without bumping
# the manifest, `git status` after this run will show
# `M lib/lead-extension.sha256` -- a built-in staleness check.
Remove-Item -LiteralPath $baselineEnv.LEAD_WORKTREE_PARENT -Recurse -Force -ErrorAction SilentlyContinue

if ($fail -gt 0) { exit 1 }
exit 0
